### ISSUE TITLE
Unable to login using external data volume

### ISSUE THREAD

**Issue by dineshpanda** [gui81/docker-alfresco#16]
My `docker-compose.yml` looks as follows:

```
version: '2'
services:
  alfresco:
    image: gui81/alfresco
    environment:
      CONTENT_STORE: /home/alfresco/content:/content
      DB_HOST: mysql
      DB_KIND: mysql
      DB_NAME: alfresco
      DB_PASSWORD: mypassword
      DB_USERNAME: root
      #LDAP_AUTH_USERNAMEFORMAT: uid=%s,cn=users,cn=accounts,dc=example,dc=com
      #LDAP_DEFAULT_ADMINS: admin
      #LDAP_ENABLED: true
      #LDAP_GROUP_SEARCHBASE: cn=groups,cn=accounts,dc=example,dc=com
      #LDAP_SECURITY_CREDENTIALS: secret
      #LDAP_SECURITY_PRINCIPAL: uid=admin,cn=users,cn=accounts,dc=example,dc=com
      #LDAP_URL: ldap://ipa.example.com:389
      #LDAP_USER_SEARCHBASE: cn=users,cn=accounts,dc=example,dc=com
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /home/alfresco/alf_data:/alfresco/alf_data
      - /home/alfresco/tomcat/logs:/alfresco/tomcat/logs
      - /home/alfresco/content:/content

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: alfresco
    image: mysql
    volumes:
      - /home/alfresco/mysqldata/mysql:/var/lib/mysql
    restart: always
```
Not able to login to Alfresco after reaching to `http://my_ip:8080/share/page` using following credentials:

username:  **admin**
password:  **admin**

If I only use container volume, then everything works fine i.e
```
volumes:
      - /alfresco/alf_data
      - /alfresco/tomcat/logs
      - /content
```

**Comment by gui81** [comment]
Try the latest version.  I did make it easier to bootstrap the data on an initial install.  Also make sure /home/alfresco/* exist and that your container has read/write permissions to those directories.

**Comment by t0xic-coder** [comment]
Same problem here with the latest version
if i try to login i get an error like:

Ihre Authentifizierungsdaten wurden nicht erkannt oder Alfresco Content Services ist zurzeit nicht verfügbar.

Your authentication data has not been detected or Alfresco Content Services is unavailable at this time.

**Comment by gui81** [comment]
I successfully used the following docker-compose.yml (similar to the one above) from scratch:
```
version: '2'
services:
  alfresco:
    image: gui81/alfresco
    environment:
      CONTENT_STORE: /content
      DB_HOST: mysql
      DB_KIND: mysql
      DB_NAME: alfresco
      DB_PASSWORD: mypassword
      DB_USERNAME: root
      LDAP_ENABLED: "false"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - [/path_to/container_data]/alfresco/alf_data:/alfresco/alf_data
      - [/path_to/container_data]/alfresco/logs:/alfresco/tomcat/logs
      - [/path_to/container_data]/alfresco/content:/content

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: alfresco
    image: mysql
    volumes:
      - [/path_to/container_data]/alfresco/mysql:/var/lib/mysql
```

Replace [/path_to/container_data] with a path that works on your system.  Also make sure you have permissions to write to your volume from the container.  I'm closing unless anyone can provide more details that proves it is an error with the image instead of operator error.
